### PR TITLE
Config Saving And Loading

### PR DESCRIPTION
**Pull request by Cosmic-SC**
I've tested this but I also made this on github and that too in like 15 minutes so dont blame me for weird crashes

### CODE REVIEW

**Comment by K-ov** [comment]
Will merge in a bit when I have time

**Comment by Cosmic-SC** [comment]
alr

**Comment by Cosmic-SC** [comment]
@K-ov this pr is now done can you review it?

**Comment by K-ov** [comment]
No 😡

**Comment by Cosmic-SC** [comment]
uhhh so should i close it?

**Comment by K-ov** [comment]
Nah leave it open I'll get to it by before Christmas 100%

**Comment by K-ov** [comment]
Stephens making a client using arsenic as a base btw if you want to help out with that

**Comment by Cosmic-SC** [comment]
> Stephens making a client using arsenic as a base btw if you want to help out with that

bro its like 50% quantum paste ask him lol

**Comment by Cosmic-SC** [comment]
> Nah leave it open I'll get to it by before Christmas 100%

real

**Comment by K-ov** [comment]
done and i also fixed up a bit to make it look nicer

**Pull request merged**
