### PR TITLE
very funny stuff (read desc btw)

### PR DESCRIPTION
**Pull request by Cosmic-SC**
### RISKY CHANGES:
launch tracker has been removed (coz its really inefficient + why would u want it?)
.idea directory has been deleted since well... u can just create it yourself when setting up workspace

ig those are the only "risky" changes ive made

### CODE REVIEW

**Comment by 1lylily** [comment]
`@Overwrite` @K-ov who taught these guys mixins wtf

**Comment by Cosmic-SC** [comment]
> `@Overwrite` @K-ov who taught these guys mixins wtf

uhhh just rewrite it if u dont like it

**Comment by Cosmic-SC** [comment]
> `@Overwrite` @K-ov who taught these guys mixins wtf

also tell me a better way of executing EventJump in a better way ill wait

**Comment by 1lylily** [comment]
an injection at TAIL...

**Comment by Cosmic-SC** [comment]
> an injection at TAIL...

how are u gonna do `float funny = e.getYaw() * 0.017453292F;` if u inject it??????

**Comment by 1lylily** [comment]
by returning the motions to their original values and doing it again... it's really not that complicated...

**Comment by Cosmic-SC** [comment]
aaaaaaaaaaa whatever rewrite that mixin if u want

**Comment by 1lylily** [comment]
i'll rewrite it after/if this is merged

**Comment by Cosmic-SC** [comment]
alr cool

**Comment by KassuK1** [comment]
First of all the WTap wont work you moved a lot of stuff to a visuals category and added AutoBlock to KA when it is a seperate module

**Comment by Cosmic-SC** [comment]
> First of all the WTap wont work you moved a lot of stuff to a visuals category and added AutoBlock to KA when it is a seperate module

1. i did not test w tap 
2. idk why i moved modules around tbh
3. the separate autoblock does not even function properly

**Comment by 1lylily** [comment]
test the code before you make a pull request

**Comment by Cosmic-SC** [comment]
> test the code before you make a pull request

ok

**Pull request closed without merging**
